### ISSUE TITLE
[Request] Add example of use in Rust

### ISSUE THREAD

**Issue by Israel-Laguan** [enquo/enquo-core#1]
The documentation in rust can be hard to approach for people just entering the library. To gain wide adoption can be helpful one or two examples that anyone can try quickly.

**Comment by mpalmer** [comment]
This is a good call.  Admittedly, the core use-case for the Rust library is to serve as a "backend" for other language bindings, but good docs are good docs regardless.  I'll try and fit in some documentation writing this week.

**Comment by mpalmer** [comment]
As of the latest batch of commits, there's now a Rust-specific README that has a few doctests demonstrating what is needed to get up and running.  Fully comprehensive module-level docs will be a mission for another time.
